version: "3"


services:       # précise les différents services (images) à utiliser 
  
  nginx:
    container_name: nginx
    build:
       context: requirements/nginx
       dockerfile: Dockerfile
    env_file: .env
    ports: 
    - "80:80"
    restart: always 

#
  wordpress:
    container_name: wordpress # Le nom du container ( doit porter le meme nom que le service d'apres le sujet )
    #Create a depedency between the 2 container, db will be launched before
    depends_on:
      - mariadb
    build:
       context: requirements/wordpress
       dockerfile: Dockerfile
    ports:
    - "80:80"             # le port, détaillé juste en dessous
    restart: always         # Permet de redémarrer automatiquement le container en cas de crash
#

  mariadb:
    container_name: mariadb
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile 
    env_file: .env
    restart: always
					