#FROM alpine:3.14

#RUN apk add --no-cache mysql-client

#ENTRYPOINT ["mysql"]
#ENTRYPOINT ["sh", "auto_config.sh"]

# Installation de WordPress

#We go the html directory
#WORKDIR /var/www/html/

# Configuration de PHP
#COPY ./conf/www.conf /etc/php8/php-fpm.d/
# Copy the .conf in the html directory
#COPY ./conf/www.conf /etc/php/7.3/fpm/pool.d/

#We expose the 9000 port
#EXPOSE 9000 
#EXPOSE 8081 ?

#CMD